INSERT INTO T_PRICE_LIST (PRICE_LIST_ID, NAME)
VALUES (1, 'Tarifa 1');
INSERT INTO T_PRICE_LIST (PRICE_LIST_ID, NAME)
VALUES (2, 'Tarifa 2');
INSERT INTO T_PRICE_LIST (PRICE_LIST_ID, NAME)
VALUES (3, 'Tarifa 3');
INSERT INTO T_PRICE_LIST (PRICE_LIST_ID, NAME)
VALUES (4, 'Tarifa 4');
INSERT INTO T_PRICE_LIST (PRICE_LIST_ID, NAME)
VALUES (5, 'Tarifa 5');